import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../globals.css';
import { Providers } from './providers';
import Header from '@/components/Header';
import Template from './template';
import BottomBar from '@/components/BottomBar';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '800'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${poppins.className} relative`}>
                <Providers>
                    <Header />
                    <Template>{children}</Template>
                    <BottomBar />
                </Providers>
            </body>
        </html>
    );
}
